# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b640b258f5f6baad6f484a0ba9667ef8d41777f098bec8dc74623ab831c9b19534afdcfc88469f8ed82d72be9475bb1efe50b730299322077091b6ac02966655

test:
  secret_key_base: bddcacc2687c957b4dc17d277aad3c10b4b212a8264aa104bdf093d7a02b311f3370900a1b520857fd6b7073408845f1f624cb43b94c856e76051575e52b99e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
